name: flutter_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_animated: ^3.2.0
  auto_animated_list: ^1.0.4
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  lottie: ^3.1.2
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  scoped_model: ^2.0.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  stacked: ^3.4.3
  stacked_themes: ^0.3.12
  todo: ^2.0.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
